# Generated by Django 4.2.7 on 2023-11-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('domain', models.CharField(max_length=128)),
                ('screenshoot', models.ImageField(default='screenshoots/default.png', upload_to='screenshoots/', verbose_name='Screenshoot')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
